name: Qodana

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3     
    
    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v2022.3.3
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

