name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v2022.3.3
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      



