name: Qodana Quality Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v5.1.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}


