name: Qodana Quality Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v5.1.0
      env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

